version: '3.4'

services:
  blazor-app:
    image: sungrow-dashboard
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:8080'
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    restart: always
